// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVsbySx6wlzTYpK_SmELqpOCzny8n09BY',
    appId: '1:674697120763:web:0025ec46f1acbcb1e0595e',
    messagingSenderId: '674697120763',
    projectId: 'my-first-project-f616c',
    authDomain: 'my-first-project-f616c.firebaseapp.com',
    storageBucket: 'my-first-project-f616c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD02nVTZv_yzSUGygAtXl7TL7wDjfFdhc8',
    appId: '1:674697120763:android:654ab00be3cd8c03e0595e',
    messagingSenderId: '674697120763',
    projectId: 'my-first-project-f616c',
    storageBucket: 'my-first-project-f616c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMyUFPhlhrlSjmesdXfXghHyijydnXlHI',
    appId: '1:674697120763:ios:4098f845e359fe95e0595e',
    messagingSenderId: '674697120763',
    projectId: 'my-first-project-f616c',
    storageBucket: 'my-first-project-f616c.appspot.com',
    iosClientId: '674697120763-m6bd24q59tr2gok6j9bkot3guv4sgeh3.apps.googleusercontent.com',
    iosBundleId: 'com.example.helloWorld',
  );
}
